--- # Ansible Playbook to automate application deployment to Raspberry Pis in a consistent and repeatable way
# Software installation and configuration
- hosts: maps_service
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    nodejs_src_dir: "{{ local_home_dir }}/dev/windfire-maps/app"
    service_name: windfire-maps
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/config.yml"
  tasks:
    ###############################################################
    ##### Windfire Maps service component deployment Section #####
    ###############################################################
    # Task 1: Stop Windfire Maps service on remote server
    - name: Stop Node.js application service {{ service_name }}
      shell: pm2 stop {{ service_name }}
      ignore_errors: yes
    
    # Task 2: Stop Windfire Security service on remote server
    - name: Delete Node.js application service {{ service_name }}
      shell: pm2 delete {{ service_name }}
      ignore_errors: yes

    # Task 3: Delete Windfire Maps directory on remote server
    - name: Clean Node.js application folder {{ remote_windfire_maps_dir }}
      file:
        path: "{{ remote_windfire_maps_dir }}"
        state: absent
    
    # Task 4: Create Windfire Maps directory on remote server and copy files
    - name: Copy Windfire Maps server component to "{{ remote_windfire_maps_dir }}" directory on remote server
      ansible.builtin.synchronize:
        src: "{{ nodejs_src_dir}}"
        dest: "{{ remote_windfire_maps_dir }}"
        rsync_opts:
          - "--exclude=ssl/windfire-maps.crt"
          - "--exclude=ssl/windfire-maps.key"
          - "--exclude=.env_PLACEHOLDER"
    
    # Task 5: Copy SSL certificate and key to remote server
    - name: Copy certificate {{ windfire_server_certificate }} from {{ local_certs_dir }} to "{{ remote_windfire_maps_dir }}/app/ssl" directory on remote server
      copy:
        src: "{{ local_certs_dir }}/{{ windfire_server_certificate }}"
        dest: "{{ remote_windfire_maps_dir }}/app/ssl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
    - name: Copy key {{ windfire_server_key }} from {{ local_certs_dir }} to "{{ remote_windfire_maps_dir }}/app/ssl" directory on remote server
      copy:
        src: "{{ local_certs_dir }}/{{ windfire_server_key }}"
        dest: "{{ remote_windfire_maps_dir }}/app/ssl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 6: Ensure remote truststore directory exists and copy Windfire Root CA certificate
    - name: Ensure remote truststore directory {{ remote_truststore_dir }} exists
      file:
        path: "{{ remote_truststore_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
        recurse: yes
    - name: Copy {{ windfire_ca_root_certificate }} to "{{ remote_truststore_dir }}" directory on remote server
      copy:
        src: "{{ local_truststore_dir }}/{{ windfire_ca_root_certificate }}"
        dest: "{{ remote_truststore_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 7: Install Node.js dependencies and start the application service
    - name: install node dependencies
      shell: npm install
      become: true
      args:
        chdir: "{{ remote_nodejs_app_dir }}"

    # Task 8: Start Node.js application service  
    - name: Start Node.js application service
      command: pm2 start app.js --name {{ service_name }}
      become: true
      args:
        chdir: "{{ remote_nodejs_app_dir }}"