--- # Ansible Playbook to automate application removal from Raspberry Pis in a consistent and repeatable way
# Software installation and configuration
- hosts: maps_service
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    service_name: windfire-maps
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/config.yml"
  tasks:
    #################################################################
    ##### Windfire Maps service component un-deployment Section #####
    #################################################################
    # Task 1: Stop Windfire Maps service on remote server
    - name: Stop Node.js application service {{ service_name }}
      shell: pm2 stop {{ service_name }}
      ignore_errors: yes
    
    # Task 2: Delete Windfire Maps service on remote server
    - name: Delete Node.js application service {{ service_name }}
      shell: pm2 delete {{ service_name }}
      ignore_errors: yes
    
    # Task 3: Delete Windfire Maps directory on remote server
    - name: Clean Node.js application folder {{ remote_windfire_maps_dir }}
      file:
        path: "{{ remote_windfire_maps_dir }}"
        state: absent