user: pi
group: pi
remote_home_dir: /home/pi
remote_homewindfiremaps_dir: "{{ remote_home_dir }}/windfire-maps"
remote_nodejs_dest_dir: "{{ remote_homewindfiremaps_dir }}"
remote_nodejs_app_dir: "{{ remote_nodejs_dest_dir }}/app"
